#!/bin/sh  
Filename=$1   
Outfilename=`basename -a $Filename`
Filesize=0    
Path=`pwd`
Dir=$Filename.Dir

if [[ -z $2 ]];then
	Size=1024 #单位MB
else
	Size=$2
fi

Subfilesize=`expr $Size \* 1024`
#验证文件名是否正确，然后计算文件的大小  

usage_print(){
	echo "Usage:"
	echo "	-h		help"
	echo '	$1		name'
	echo '	$2		size(M)'	
	echo -e "\n	Split the file."
}

if [[ -z $Filename || $1 == '-h' || $1 == '--help' ]];then 
	usage_print
	exit 
fi 
if [ -e $Filename ];then 
   Filesize=`du -b $Filename | awk '{print $1}'` 
     if [ $Filesize == 0 ];then 
        echo "Error:The File size is zero!" 
        exit 
     fi 
   echo "The file size is $Filesize Byte" 
else 
   echo "Error:$Filename does not exist!" 
   exit  
fi
 
#计算需要分割为几个文件 
SubfileByte=`expr $Subfilesize \* 1024`
Subfilenum=`expr $Filesize / $SubfileByte`
if [ `expr $Filesize % $Subfilesize` -ne 0 ];then
   Subfilenum=`expr $Subfilenum + 1`
fi    

#将文件分割  
echo "$Filename will be divided into $Subfilenum" 
i=1
skipnum=0
mkdir -p $Path/$Dir
while [ $i -le $Subfilenum ]
    do
      echo "$Outfilename$i.img"
      dd if=$Filename of="$Path/$Dir/$Outfilename.d$i" bs=1024 count=$Subfilesize skip=$skipnum
      i=`expr $i + 1`
      skipnum=`expr $skipnum + $Subfilesize`
    done
echo "$Filename has been divided into $Subfilenum"
echo "Done !" 
